### ISSUE TITLE
missing speech features for LSMDC dataset

### ISSUE THREAD

**Issue by boalantvxqpku** [gabeur/mmt#13]
Hi, thanks for sharing the code.

I noticed that the speech features are missing for all video clips in the LSMDC.tar.gz. But the paper mentioned that 
![image](https://user-images.githubusercontent.com/37374946/114879076-734ed900-9e33-11eb-8eec-71ac0a5a47a1.png)

I watched some original video clips from LSMDC dataset and found that they are all with audio where speech transcripts can be extracted using the Google Cloud Speech to Text API.

Therefore, my question is that did you train the MMT model with speech features on LSMDC dataset. If so, what's the result and would you please share the speech feature files? If not, why did't you utilize the speech features?

I would appreciate your reply.

**Comment by gabeur** [comment]
We used the features provided by the authors of [Collaborative Experts](https://www.robots.ox.ac.uk/~vgg/research/collaborative-experts/). Figure 1 of their paper shows that they did not extract speech features even if the audio is present. Probably it is not fair to use speech for the LSMDC dataset because some captions where created from the movie script and therefore contain the video speech.

That is why it is missing from the LSMDC.tar.gz file and therefore our model does not use speech on that dataset, we should correct that in the paper.
