### ISSUE TITLE
How to train MMT from scratch for other databases e.g. v3c1

### ISSUE THREAD

**Issue by varsha-devi** [gabeur/mmt#15]
First of all, thanks a lot for sharing such a great work. It is really interesting reading your paper and work. 

Furthermore, If I want to analyze the performance of MMT on other databases like V3C1, how will I extract the expert embeddings for raw videos. Do I have to extract them on my own first and your code can only work for pre-computed features? or your code also extracts the experts features from videos?
As in the code, pre-computed features for databases e.g. MSRVTT, LSMDC are provided and it does not seem that there is any file for extracting embedded features from pretrained experts that you used. 

Is this possible for you to share the "models (pre-trained experts) and code" you used for extracting expert embedding from videos.

**Comment by gabeur** [comment]
Sorry, we will not provide the features extraction code.
We mainly used the features provided by [Collaborative Experts](https://github.com/albanie/collaborative-experts) so we did not extract them ourselves.
Also, we made the extracted features used in this paper available at [this page](http://thoth.inrialpes.fr/research/video-features) so that you don't have to extract them yourself in order to reproduce the results.
If you want to evaluate the performance of MMT on another dataset, you will have to extract the features yourself. The MMT model is agnostic as to the pre-trained experts used to extract the features.
