### ISSUE TITLE
Feature extraction code

### ISSUE THREAD

**Issue by WenZheWang** [gabeur/mmt#5]
Hi,
Could you please provide the feature extraction code.

**Comment by gabeur** [comment]
Sorry, we will not provide the features extraction code.
We mainly used the features provided by [Collaborative Experts](https://github.com/albanie/collaborative-experts) so we did not extract them ourselves.
Regarding the S3D features, the checkpoint to extract them is available [here](https://github.com/princeton-vl/d3dhelper/blob/master/d3d_helper.ipynb).
Also, we made the extracted features available at [this page](http://thoth.inrialpes.fr/research/video-features) so that you don't have to extract them yourself in order to reproduce the results.
